### 登录 zhangsan
POST {{host}}/auth/login
content-type: application/json

{
  "username": "test001",
  "password": "password"
}

> {%
    client.global.set("token", response.body.access_token);
%}

### 登出
POST {{host}}/auth/logout
Authorization: Bearer {{token}}

### Change password
POST {{host}}/auth/change-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "old_password": "password",
  "new_password": "password2"
}