### Create a new game server
POST {{host}}/game_server/
Authorization: Bearer {{token}}
content-type: application/json

{
  "address": "localhost:1",
  "name": "Server {{$random.integer}}",
  "description": "",
  "reporter_host": "127.0.0.1",
  "detail": "1a23"
}

### Get server
GET {{host}}/game_server/
Authorization: Bearer {{token}}

### Patch server #1
PATCH {{host}}/game_server/1
Authorization: Bearer {{token}}
content-type: application/json

{
  "address": "localhost:123"
}

### Delete server #1
DELETE {{host}}/game_server/1
Authorization: Bearer {{token}}


### Report
POST {{host}}/game_server/report/1
User-Agent: Rdfz3D HTTP Client
content-type: application/json

{
  "player_count": 1,
  "state": "running",
  "game_time": "2025-02-21T14:11:17.574",
  "day_length": 1,
  "night_length": 1,
  "detail": "string"
}
