### 注册 zhangsan
POST {{host}}{{auth_prefix}}/register
content-type: application/json

{
  "username": "zhangsan",
  "email": "zhangsan@example.com",
  "phone_no": "1",
  "password": "password"
}

### 登录 zhangsan
POST {{host}}{{auth_prefix}}/login
content-type: application/x-www-form-urlencoded

username=zhangsan&password=password

> {%
    client.global.set("token", response.body.access_token);
%}

### 登出
POST {{host}}{{auth_prefix}}/logout
Authorization: Bearer {{token}}

### 获取用户信息
GET {{host}}{{auth_prefix}}/me
Authorization: Bearer {{token}}

### 修改自己的手机号
PATCH {{host}}{{auth_prefix}}/me
Authorization: Bearer {{token}}
content-type: application/json

{
  "phone_no": "+86 135-1128-8028"
}

### 修改自己的邮箱
PATCH {{host}}{{auth_prefix}}/me
Authorization: Bearer {{token}}
content-type: application/json

{
  "email": " {{$random.email}}"
}
